#!/bin/bash

# Direct Netlify environment variable setup using their web interface automation

SITE_NAME="thunderous-jalebi-6f0dc7"
ENV_KEY="VITE_GADM_BASE_URL"
ENV_VALUE="https://baqlxgwdfjltivlfmsbr.supabase.co/storage/v1/object/public/geo"

echo "🌐 Netlify Environment Variable Setup"
echo "===================================="
echo ""
echo "Since CLI authentication is complex, here's a quick way to add the env var:"
echo ""
echo "1. Click this direct link to your site's env settings:"
echo "   👉 https://app.netlify.com/sites/$SITE_NAME/settings/env"
echo ""
echo "2. Click 'Add a variable'"
echo ""
echo "3. Copy and paste these values:"
echo "   Key:   $ENV_KEY"
echo "   Value: $ENV_VALUE"
echo ""
echo "4. Click 'Save'"
echo ""
echo "5. Redeploy your site:"
echo "   👉 https://app.netlify.com/sites/$SITE_NAME/deploys"
echo "   Click 'Trigger deploy' → 'Clear cache and deploy site'"
echo ""
echo "That's it! Your maps will load without CORS errors."
echo ""
echo "📋 For copy-paste convenience:"
echo "================================"
echo "$ENV_KEY"
echo "$ENV_VALUE"
echo "================================"