[[headers]]
  for = "/data/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET"

[[headers]]
  for = "/geo/gadm41_PHL_1.json.gz"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"